% 新建一个文件: get_eoh_prompts.m
function prompts = get_eoh_prompts()
    % 基础任务描述
    prompts.task = [
        '任务：我正在使用遗传算法求解TSP（旅行商问题）。', ...
        '请你帮我设计一个新的启发式交叉算子（Crossover Operator），', ...
        '用来将两个优秀的父代路径结合，生成两个更优秀的子代路径。', ...
        '最终目标是最小化TSP的路径总距离。'
    ];

    % 函数接口定义与严格约束（至关重要！）
    prompts.io_constraints = [
        '你必须提供一段 MATLAB 代码，函数名为 llm_smart_crossover。\n', ...
        '输入参数为：p1 (父代1的城市序列, 1xn数组), p2 (父代2的城市序列, 1xn数组)。\n', ...
        '输出参数为：c1, c2 (生成的两个子代城市序列, 1xn数组)。\n', ...
        '【绝对约束 1】：c1 和 c2 必须是 1 到 n 的严格全排列，即每个城市必须且只能出现一次，绝不能有遗漏或重复！\n', ...
        '【绝对约束 2】：绝对禁止在代码最后面定义额外的局部子函数（Local Functions）。所有的辅助逻辑必须全部写在 llm_smart_crossover 主函数体内，或者使用句柄/匿名函数（如 @(x)...），否则会导致系统调用崩溃！'
        
    ];

    % 1. Initialization (初始生成) 提示词模板
    prompts.init = sprintf('%s\n%s\n%s', ...
        prompts.task, ...
        prompts.io_constraints, ...
        '请直接输出 MATLAB 代码，代码请放在 ```matlab 和 ``` 之间，并在代码开头用注释简述你的策略思路，不要输出任何额外的解释文本。');

    % 2. Evolution M1 (单体变异/改进) 提示词模板
    % 需要在代码中用 sprintf 替换 %s
    prompts.m1_template = [
        prompts.task, '\n', ...
        '我已经有一个表现不错的交叉算子，其代码如下：\n', ...
        '```matlab\n%s\n```\n', ... % 这里留给当前最好的代码
        '请在这个策略的基础上进行改进，设计一个更新、更高效的交叉策略，进一步缩短路径距离。\n', ...
        prompts.io_constraints, '\n', ...
        '请直接输出 MATLAB 代码，代码请放在 ```matlab 和 ``` 之间，并在代码开头用注释简述你的改进思路。'
    ];

    % 3. Evolution E2 (提取共性并创新) 提示词模板
    prompts.e2_template = [
        prompts.task, '\n', ...
        '我有两个表现较好的交叉算子策略，代码分别如下：\n', ...
        '【算子1】:\n```matlab\n%s\n```\n', ...
        '【算子2】:\n```matlab\n%s\n```\n', ...
        '请先提取这两个策略中的核心优秀思想，然后结合它们，创造出一个全新的交叉算子。\n', ...
        prompts.io_constraints, '\n', ...
        '请直接输出 MATLAB 代码，代码请放在 ```matlab 和 ``` 之间，并在代码开头用注释简述你的融合思路。'
    ];
end